apiVersion: v1
kind: Service
metadata:
  name: lifecycle-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    name: lifecycle-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-service-deployment
spec:
  selector:
    matchLabels:
      name: lifecycle-service
  replicas: 1
  template:
    metadata:
      labels:
        name: lifecycle-service
    spec:
      containers:
       - name: lifecycle-service
         image: cratekube/lifecycle-service:latest
         ports:
         - containerPort: 9000
         volumeMounts:
         - mountPath: /app/kube/kubeconfig
           name: kube-config-volume
         env:
          - name: ADMIN_APIKEY
            valueFrom:
             secretKeyRef:
              name: cratekube-api-secret
              key: admin-api-key
      volumes:
        - name: kube-config-volume
          hostPath:
           path: /var/lib/cratekube/kubeconfig
